# Chances are simple. 1 means a 1 in 1 chance of getting it, or 100%. 3000 means a 1 in 3000 chance

AquaticHoe:
  Chances:
    FarmKey: 1000000
    StackOfCrops: 2000
    AxolotlSpawnEgg: 5000
    FrogSpawnEgg: 3000
Global:
  Prefix: '&b&lSURVIVAL &8&lâ–¶ '
AntiDrop:
  Enabled: true
  RequiredDropCount: 2
  ExpireDuration: 2
  Message: "&fDrop %amount% more time(s) to drop!"
ItemFrameToInv:
  Enabled: true
  Message: "&cInventory is full!"
TrashCommand:
  Enabled: true
  InventoryName: "Trash"
  Message: "&cYou cannot trash non vanilla items!"